apiVersion: v2
name: nexus-ai
description: Nexus AI Framework - Advanced Game AI Automation Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - ai
  - gaming
  - automation
  - machine-learning
  - reinforcement-learning
home: https://github.com/neophrythe/Nexus-AI-Framework
sources:
  - https://github.com/neophrythe/Nexus-AI-Framework
maintainers:
  - name: Nexus Team
    email: support@nexus-ai.io
icon: https://nexus-ai.io/logo.png
dependencies:
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: prometheus
    version: "15.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled